os: osx
dist: trusty
language: generic

sudo: false

before_install:
 - brew update
 - which python3 || brew install python3
 - pip3 install numpy
 - brew unlink boost || echo 'brew: boost not installed'
 - brew unlink boost-python3 || echo 'brew: boost-python3 not installed'

matrix:
  include:
    - install: travis_wait 180 brew install ./Formula/boost\@1.70.rb ./Formula/boost-python3\@1.70.rb ./Formula/rdkit.rb --HEAD --build-from-source --with-python3 --without-numpy
      env:
        - version=HEAD HOMEBREW_DEVELOPER=1
    - install: travis_wait 180 brew install ./Formula/boost\@1.70.rb ./Formula/boost-python3\@1.70.rb ./Formula/rdkit.rb --build-from-source --with-python3 --without-numpy
      env:
        - version=current HOMEBREW_DEVELOPER=1
