os: osx
dist: trusty
language: generic

sudo: false

before_install:
 - brew update
 - brew install python3
 - pip install numpy
 - pip3 install numpy

install:
 - travis_wait 30 brew install ./Formula/rdkit.rb --HEAD --build-from-source --with-python3 --without-numpy